kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: quantum-ui
  name: quantum-ui
  namespace: {{ namespace }}
spec:
  template:
    metadata:
      labels:
        app: quantum-ui
      name: quantum-ui
    spec:
      containers:
        - name: quantum-ui
          image: sr-rnd-105.swg.local:5000/ng-ui-quantum:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP