apiVersion: v1
kind: ConfigMap
metadata:
  name: quantum-ui-config
  namespace: {{ namespace }}
  labels:
    k8s-app: quantum-ui
data:
  appConfig.json: |-
    {
      "protocol": "http",
      "port": "80",
      "host": "gateway.quantum.{{ k8s_node }}",
      "apiUrl": "http://gateway.quantum.{{ k8s_node }}:80",
      "webSocketUrl": "ws://gateway.quantum.{{ k8s_node }}:80/dashboard/ws",
      "wsProtocol": "Bearer"
    }
